FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    torch --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir -r requirements.txt

COPY ui ui
COPY data data

EXPOSE 8501

CMD ["streamlit","run","ui/app.py","--server.address=0.0.0.0"]